Script started on 2016年03月13日 (週日) 13時55分36秒
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ whoami; pwd
F74042117
/home/F74042117
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ gut config -l
No command 'gut' found, did you mean:
 Command 'cut' from package 'coreutils' (main)
 Command 'gout' from package 'scotch' (universe)
 Command 'git' from package 'git' (main)
 Command 'gpt' from package 'gpt' (universe)
 Command 'gst' from package 'gnu-smalltalk' (universe)
gut: command not found
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ git config -l
user.name=asdsdlgl
user.email=zegretage@gmail.com
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ ls
[0m[01;34mlab1[0m  lab1.script
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ ig[K[Kgit clone g[Khttps://git [Khub.com/asdsdlgl/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74042117@2015cpp: ~[01;32mF74042117@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月13日 (週日) 13時56分36秒
